TEAMS: dict[str, str] = {
    "ARI": "ARIZONA",
    "ATL": "ATLANTA",
    "BAL": "BALTIMORE",
    "BUF": "BUFFALO",
    "CAR": "CAROLINA",
    "CHI": "CHICAGO",
    "CIN": "CINCINNATI",
    "CLE": "CLEVELAND",
    "DAL": "DALLAS",
    "DEN": "DENVER",
    "DET": "DETROIT",
    "GB": "GREEN BAY",
    "HOU": "HOUSTON",
    "IND": "INDIANAPOLIS",
    "JAX": "JACKSONVILLE",
    "KC": "KANSAS CITY",
    "LV": "LAS VEGAS",
    "LAC": "LOS ANGELES CHARGERS",
    "LAR": "LOS ANGELES RAMS",
    "MIA": "MIAMI",
    "MIN": "MINNESOTA",
    "NE": "NEW ENGLAND",
    "NO": "NEW ORLEANS",
    "NYG": "NEW YORK GIANTS",
    "NYJ": "NEW YORK JETS",
    "PHI": "PHILADELPHIA",
    "PIT": "PITTSBURGH",
    "SF": "SAN FRANCISCO",
    "SEA": "SEATTLE",
    "TB": "TAMPA BAY",
    "TEN": "TENNESSEE",
    "WAS": "WASHINGTON",
}

NAME_TO_ABBR = {name: abbr for abbr, name in TEAMS.items()}
