/** Lista fija de los 32 equipos (misma nomenclatura que el backend). */
export const NFL_TEAMS: { abbr: string; name: string; gridLabel: string }[] = [
  { abbr: "ARI", name: "ARIZONA", gridLabel: "AZ" },
  { abbr: "ATL", name: "ATLANTA", gridLabel: "ATL" },
  { abbr: "BAL", name: "BALTIMORE", gridLabel: "BAL" },
  { abbr: "BUF", name: "BUFFALO", gridLabel: "BUF" },
  { abbr: "CAR", name: "CAROLINA", gridLabel: "CAR" },
  { abbr: "CHI", name: "CHICAGO", gridLabel: "CHI" },
  { abbr: "CIN", name: "CINCINNATI", gridLabel: "CIN" },
  { abbr: "CLE", name: "CLEVELAND", gridLabel: "CLE" },
  { abbr: "DAL", name: "DALLAS", gridLabel: "DAL" },
  { abbr: "DEN", name: "DENVER", gridLabel: "DEN" },
  { abbr: "DET", name: "DETROIT", gridLabel: "DET" },
  { abbr: "GB", name: "GREEN BAY", gridLabel: "GB" },
  { abbr: "HOU", name: "HOUSTON", gridLabel: "HOU" },
  { abbr: "IND", name: "INDIANAPOLIS", gridLabel: "IND" },
  { abbr: "JAX", name: "JACKSONVILLE", gridLabel: "JAX" },
  { abbr: "KC", name: "KANSAS CITY", gridLabel: "KC" },
  { abbr: "LV", name: "LAS VEGAS", gridLabel: "LV" },
  { abbr: "LAC", name: "LOS ANGELES CHARGERS", gridLabel: "LAC" },
  { abbr: "LAR", name: "LOS ANGELES RAMS", gridLabel: "LAR" },
  { abbr: "MIA", name: "MIAMI", gridLabel: "MIA" },
  { abbr: "MIN", name: "MINNESOTA", gridLabel: "MIN" },
  { abbr: "NE", name: "NEW ENGLAND", gridLabel: "NE" },
  { abbr: "NO", name: "NEW ORLEANS", gridLabel: "NO" },
  { abbr: "NYG", name: "NEW YORK GIANTS", gridLabel: "NYG" },
  { abbr: "NYJ", name: "NEW YORK JETS", gridLabel: "NYJ" },
  { abbr: "PHI", name: "PHILADELPHIA", gridLabel: "PHI" },
  { abbr: "PIT", name: "PITTSBURGH", gridLabel: "PIT" },
  { abbr: "SF", name: "SAN FRANCISCO", gridLabel: "SF" },
  { abbr: "SEA", name: "SEATTLE", gridLabel: "SEA" },
  { abbr: "TB", name: "TAMPA BAY", gridLabel: "TB" },
  { abbr: "TEN", name: "TENNESSEE", gridLabel: "TEN" },
  { abbr: "WAS", name: "WASHINGTON", gridLabel: "WAS" },
];
